// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.abosen.netty.example07.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.abosen.protobuf.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   * @return The realname.
   */
  String getRealname();
  /**
   * <code>string realname = 1;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
